### ISSUE TITLE
screen size

### ISSUE THREAD

**Issue by seal62** [wendzhue/wz_wireframe_kit_sketch#1]
Hi, your wireframe looks great. I am slightly confused by the screen size you are using though. The iphone 6 has a screen resolution of 750x1334px but your template is setup with 376x664px. Is there a particular reason for this?

thanks

**Comment by wzhudev** [comment]
Hi, I am glad you like it.  No particular reason for using the 375*667 resolution. I design using this resolution and export @2x slices. But it seems that I made some mistakes when zooming it, so we got 376 and 664 here... I will fix that.
